'use strict';
const BASE='https://rknmkwnlsaknmtwxupvf.supabase.co';
const KEY='sb_publishable_jeNI0OZSFYutImREvNNHFw_-JNnRf--';
const STAGES=['NEW','IN_PROGRESS','WAITING','BLOCKED','RESOLVED','CLOSED'];
const LANG={
 ar:{dashboard:'لوحة المتابعة',myTasks:'تاسكاتي',allTasks:'كل التاسكات',kanban:'كانبان',calendar:'التقويم',reports:'التقارير',users:'المستخدمون والصلاحيات',settings:'الإعدادات',newTask:'تاسك جديد',search:'ابحث في التاسكات...',filters:'فلترة',groupBy:'تجميع حسب',favorites:'المفضلة',open:'مفتوحة',inProgress:'قيد العمل',waiting:'انتظار',blocked:'متوقفة',resolved:'تم الحل',closed:'مغلقة',total:'الإجمالي',recent:'أحدث التاسكات',priority:'الأولوية',status:'الحالة',assignee:'المسؤول',dueDate:'تاريخ الاستحقاق',updated:'آخر تحديث',project:'المشروع',title:'العنوان',description:'الوصف',save:'حفظ',cancel:'إلغاء',edit:'تعديل',details:'التفاصيل',analysis:'التحليل والتشخيص',solution:'الحل والتنفيذ',history:'الهيستوري',access:'الصلاحيات',activity:'النشاط',addNote:'إضافة ملاحظة',logout:'خروج',team:'الفريق',language:'اللغة',theme:'المظهر',dark:'داكن',light:'فاتح',arabic:'العربية',english:'English',welcome:'مرحبًا بك',today:'اليوم',upcoming:'المواعيد القادمة',byStatus:'التاسكات حسب الحالة',byPriority:'حسب الأولوية',mine:'الخاصة بي',assigned:'مسندة للآخرين',watching:'للمراجعة',list:'قائمة',create:'إنشاء',signIn:'تسجيل الدخول',email:'البريد الإلكتروني',password:'كلمة المرور',firstAdmin:'إعداد أول Admin',name:'الاسم',setupKey:'مفتاح الإعداد',invite:'دعوة مستخدم',reviewer:'مراجع',admin:'مدير النظام',member:'مستخدم',noTasks:'لا توجد تاسكات',actions:'إجراءات',startDate:'تاريخ البدء',createdBy:'أنشأها',closeDate:'تاريخ الإغلاق',task:'التاسك',taskDetails:'تفاصيل التاسك'},
 en:{dashboard:'Dashboard',myTasks:'My Tasks',allTasks:'All Tasks',kanban:'Kanban',calendar:'Calendar',reports:'Reports',users:'Users & Access',settings:'Settings',newTask:'New Task',search:'Search tasks...',filters:'Filters',groupBy:'Group By',favorites:'Favorites',open:'Open',inProgress:'In Progress',waiting:'Waiting',blocked:'Blocked',resolved:'Resolved',closed:'Closed',total:'Total',recent:'Recent Tasks',priority:'Priority',status:'Status',assignee:'Assignee',dueDate:'Due Date',updated:'Updated',project:'Project',title:'Title',description:'Description',save:'Save',cancel:'Cancel',edit:'Edit',details:'Details',analysis:'Analysis & Diagnosis',solution:'Solution & Implementation',history:'History',access:'Access',activity:'Activity',addNote:'Add Note',logout:'Logout',team:'Team',language:'Language',theme:'Theme',dark:'Dark',light:'Light',arabic:'العربية',english:'English',welcome:'Welcome back',today:'Today',upcoming:'Upcoming Deadlines',byStatus:'Tasks by Status',byPriority:'Tasks by Priority',mine:'Mine',assigned:'Assigned to Others',watching:'Watching',list:'List',create:'Create',signIn:'Sign in',email:'Email',password:'Password',firstAdmin:'Setup First Admin',name:'Name',setupKey:'Setup Key',invite:'Invite User',reviewer:'Reviewer',admin:'Administrator',member:'User',noTasks:'No tasks found',actions:'Actions',startDate:'Start Date',createdBy:'Created By',closeDate:'Closed Date',task:'Task',taskDetails:'Task Details'}
};
const app=document.getElementById('app');
let session=null,me=null,tasks=[],profiles=[],access=[],historyCache={};
let state={page:'dashboard',view:'list',query:'',status:'',priority:'',mine:false,tab:'details',selected:null,sidebar:false};
let prefs={lang:localStorage.getItem('td_lang')||'ar',theme:localStorage.getItem('td_theme')||'light'};
const t=k=>LANG[prefs.lang][k]||k;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials=v=>String(v||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const fmt=d=>d?new Intl.DateTimeFormat(prefs.lang==='ar'?'ar-KW':'en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(d)):'—';
const rel=d=>{if(!d)return '—';let x=Math.max(0,Date.now()-new Date(d).getTime()),h=Math.floor(x/36e5);if(h<1)return prefs.lang==='ar'?'الآن':'now';if(h<24)return prefs.lang==='ar'?`منذ ${h} س`:`${h}h ago`;let days=Math.floor(h/24);return prefs.lang==='ar'?`منذ ${days} يوم`:`${days}d ago`};
const stageLabel=s=>({NEW:prefs.lang==='ar'?'جديدة':'New',IN_PROGRESS:t('inProgress'),WAITING:t('waiting'),BLOCKED:t('blocked'),RESOLVED:t('resolved'),CLOSED:t('closed'),CANCELLED:prefs.lang==='ar'?'ملغاة':'Cancelled'}[s]||s);
const priorityLabel=p=>({LOW:prefs.lang==='ar'?'منخفضة':'Low',MEDIUM:prefs.lang==='ar'?'متوسطة':'Medium',HIGH:prefs.lang==='ar'?'عالية':'High',URGENT:prefs.lang==='ar'?'عاجلة':'Urgent'}[p]||p);
const icon=(name,size=18)=>{const P={dash:'<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/>',task:'<rect x="4" y="4" width="16" height="16" rx="2"/><path d="M8 9h8M8 13h8M8 17h5"/>',kanban:'<rect x="3" y="4" width="5" height="16" rx="1"/><rect x="10" y="4" width="5" height="11" rx="1"/><rect x="17" y="4" width="4" height="8" rx="1"/>',cal:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4M16 3v4M3 10h18"/>',chart:'<path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/>',users:'<circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2"/><path d="M3 20c0-4 2-7 6-7s6 3 6 7M15 14c4 0 6 2 6 5"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21h-4v-.1A1.7 1.7 0 0 0 8.6 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-.6-1A1.7 1.7 0 0 0 2.9 13.6H3v-4h-.1A1.7 1.7 0 0 0 4.6 8.6a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1.1V3h4v.1a1.7 1.7 0 0 0 1 1.5 1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9c.1.4.3.8.6 1 .3.2.7.4 1.1.4H21v4h-.1a1.7 1.7 0 0 0-1.5.6z"/>',plus:'<path d="M12 5v14M5 12h14"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',list:'<path d="M8 6h13M8 12h13M8 18h13"/><circle cx="3" cy="6" r="1"/><circle cx="3" cy="12" r="1"/><circle cx="3" cy="18" r="1"/>',moon:'<path d="M21 12.7A8.5 8.5 0 1 1 11.3 3 7 7 0 0 0 21 12.7z"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',back:'<path d="M19 12H5M12 19l-7-7 7-7"/>',mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/>',filter:'<path d="M4 5h16l-6 7v5l-4 2v-7z"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>'};return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${P[name]||P.task}</svg>`};
function applyPrefs(){document.documentElement.dataset.theme=prefs.theme;document.documentElement.lang=prefs.lang;document.documentElement.dir=prefs.lang==='ar'?'rtl':'ltr';document.querySelector('meta[name="theme-color"]')?.setAttribute('content',prefs.theme==='dark'?'#1b1f24':'#714B67')}
function toast(msg){const d=document.createElement('div');d.className='toast';d.textContent=msg;document.getElementById('toast-root').append(d);setTimeout(()=>d.remove(),2600)}
function saveSession(x){session=x;localStorage.setItem('td_session',JSON.stringify(x))}function loadSession(){try{session=JSON.parse(localStorage.getItem('td_session')||'null')}catch{session=null}}function clearSession(){session=null;localStorage.removeItem('td_session')}
async function refresh(){if(!session?.refresh_token)throw Error('Session expired');const r=await fetch(`${BASE}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});const d=await r.json();if(!r.ok)throw Error(d.error_description||d.msg||'Session expired');saveSession(d);return d}
