const JSON_HEADERS={"content-type":"application/json;charset=UTF-8"};
const SCHEMA={type:"object",properties:{action:{type:"string",enum:["CREATE_TASK","UPDATE_TASK","ADD_HISTORY","QUERY_TASKS","HELP","UNKNOWN"]},task_number:{type:["integer","null"]},title:{type:["string","null"]},description:{type:["string","null"]},analysis:{type:["string","null"]},diagnosis:{type:["string","null"]},resolution:{type:["string","null"]},status:{type:["string","null"],enum:["NEW","IN_PROGRESS","WAITING","BLOCKED","RESOLVED","CLOSED",null]},priority:{type:["string","null"],enum:["LOW","MEDIUM","HIGH","URGENT",null]},history_title:{type:["string","null"]},history_details:{type:["string","null"]},requires_confirmation:{type:"boolean"},reply:{type:"string"}},required:["action","task_number","title","description","analysis","diagnosis","resolution","status","priority","history_title","history_details","requires_confirmation","reply"]};

function need(env,k){const v=env[k];if(!v)throw new Error(`${k}_NOT_CONFIGURED`);return v}
function b64url(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replaceAll("+","-").replaceAll("/","_").replace(/=+$/g,"")}
async function derive(env,label,len=32){const raw=new TextEncoder().encode(`${label}:${need(env,"TELEGRAM_BOT_TOKEN")}`);const d=new Uint8Array(await crypto.subtle.digest("SHA-256",raw));return b64url(d).slice(0,len)}
async function botPassword(env){return `${await derive(env,"taskdesk-bot-password",28)}Aa1!`}
async function webhookSecret(env){return derive(env,"telegram-webhook",32)}
async function pairCode(env){const raw=new TextEncoder().encode(`pair:${need(env,"TELEGRAM_BOT_TOKEN")}`);const d=new Uint8Array(await crypto.subtle.digest("SHA-256",raw));const n=((d[0]<<24)>>>0)+(d[1]<<16)+(d[2]<<8)+d[3];return String(n%1000000).padStart(6,"0")}
function tgUrl(env,method){return `https://api.telegram.org/bot${need(env,"TELEGRAM_BOT_TOKEN")}/${method}`}
async function telegram(env,method,body){const r=await fetch(tgUrl(env,method),{method:"POST",headers:JSON_HEADERS,body:JSON.stringify(body)});const d=await r.json();if(!d.ok)throw new Error(d.description||"Telegram error");return d.result}
async function say(env,chatId,text,extra={}){return telegram(env,"sendMessage",{chat_id:chatId,text,parse_mode:"HTML",disable_web_page_preview:true,...extra})}
function esc(s=""){return String(s).replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]))}

async function auth(env){const email=need(env,"SUPABASE_BOT_EMAIL"),password=await botPassword(env);const login=async()=>{const r=await fetch(`${env.SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:env.SUPABASE_ANON_KEY,...JSON_HEADERS},body:JSON.stringify({email,password})});const d=await r.json();return {ok:r.ok,data:d}};let x=await login();if(x.ok&&x.data?.access_token)return x.data;const sr=await fetch(`${env.SUPABASE_URL}/auth/v1/signup`,{method:"POST",headers:{apikey:env.SUPABASE_ANON_KEY,...JSON_HEADERS},body:JSON.stringify({email,password,data:{full_name:"TaskDesk Telegram Bot"}})});const sd=await sr.json();if(sr.ok&&sd.access_token)return sd;if(sr.ok&&sd.user&&!sd.access_token)throw new Error("EMAIL_CONFIRMATION_REQUIRED");throw new Error(sd?.msg||sd?.message||sd?.error_description||x.data?.message||x.data?.error_description||"Supabase login failed")}
async function sb(env,token,path,{method="GET",body,prefer}={}){const h={apikey:env.SUPABASE_ANON_KEY,authorization:`Bearer ${token}`};if(body!==undefined)Object.assign(h,JSON_HEADERS);if(prefer)h.Prefer=prefer;const r=await fetch(`${env.SUPABASE_URL}/rest/v1/${path}`,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.hint||`Supabase ${r.status}`);return d}
async function botContext(env){const a=await auth(env);const token=a.access_token,user=a.user;const ps=await sb(env,token,`profiles?id=eq.${user.id}&select=*`);return {token,user,profile:ps?.[0]||null}}

async function config(env,ctx){const rows=await sb(env,ctx.token,`tasks?title=eq.__TELEGRAM_CONFIG__&created_by=eq.${ctx.user.id}&archived=eq.true&select=*`);if(!rows?.length)return null;try{return JSON.parse(rows[0].description||"{}")}catch{return null}}
async function claim(env,ctx,from,chatId,code){if(String(code||"")!==await pairCode(env))throw new Error("Invalid pairing code.");const c=await config(env,ctx);if(c?.telegram_user_id&&String(c.telegram_user_id)!==String(from.id))throw new Error("This bot is already paired with another Telegram account.");if(!c){await sb(env,ctx.token,"tasks",{method:"POST",prefer:"return=representation",body:{title:"__TELEGRAM_CONFIG__",description:JSON.stringify({telegram_user_id:from.id,chat_id:chatId,username:from.username||null,paired_at:new Date().toISOString()}),status:"CLOSED",priority:"LOW",start_date:new Date().toISOString().slice(0,10),created_by:ctx.user.id,updated_by:ctx.user.id,archived:true}})}return true}
async function ensureOwner(env,ctx,from){const c=await config(env,ctx);return !!c&&String(c.telegram_user_id)===String(from.id)}

async function interpret(env,text){const system=`You are TaskDesk Copilot. The user may speak Egyptian/Gulf Arabic, English, mixed Arabic-English, or informal shorthand. Convert the request into ONE safe structured action. Create concise professional business wording. Default saved task content language: professional English unless the user explicitly requests Arabic. Never invent facts. For an update or history request, require a task number if it is not clear. Closing requires explicit confirmation such as confirm/confirmed/أكد/تأكيد; otherwise requires_confirmation=true. Status mapping: جديد=NEW, شغال/قيد العمل=IN_PROGRESS, انتظار/مستني=WAITING, blocked/متوقف=BLOCKED, اتحل=RESOLVED, اقفل/closed=CLOSED. Return only schema JSON.`;try{const out=await env.AI.run(env.AI_MODEL||"@cf/meta/llama-3.1-8b-instruct-fast",{messages:[{role:"system",content:system},{role:"user",content:text}],response_format:{type:"json_schema",json_schema:SCHEMA},temperature:.2,max_tokens:700});const r=out?.response;return typeof r==="string"?JSON.parse(r):r}catch(e){console.log(JSON.stringify({event:"ai_fallback",message:String(e?.message||e)}));return fallbackInterpret(text)}}
function norm(s){return String(s||"").toLowerCase().replace(/[إأآ]/g,"ا").replace(/ة/g,"ه").replace(/ى/g,"ي").replace(/ـ/g,"").replace(/\s+/g," ").trim()}
function taskNo(text){const m=String(text).match(/(?:task|تاسك|case|كي(?:س|يس)|#)\s*#?\s*(\d{1,9})/i)||String(text).match(/#(\d{1,9})/);return m?Number(m[1]):null}
function fallbackInterpret(text){const t=norm(text),n=taskNo(text);let status=null,priority=null;if(/(اقفل|اغلق|closed?|complete)/i.test(t))status="CLOSED";else if(/(resolved?|اتحل|تم الحل)/i.test(t))status="RESOLVED";else if(/(blocked?|متوقف|واقف)/i.test(t))status="BLOCKED";else if(/(waiting|انتظار|مستني)/i.test(t))status="WAITING";else if(/(in progress|شغال|قيد العمل)/i.test(t))status="IN_PROGRESS";if(/(urgent|critical|عاجل جدا|ضروري جدا)/i.test(t))priority="URGENT";else if(/(high priority|اولويه عاليه|عاجل)/i.test(t))priority="HIGH";else if(/(low priority|اولويه منخفضه|مش مستعجل)/i.test(t))priority="LOW";const query=/(وريني|اعرض|هات|list|show)/i.test(t);const update=!!n;return {action:query?"QUERY_TASKS":update?"ADD_HISTORY":"CREATE_TASK",task_number:n,title:update?null:"TaskDesk Request",description:update?null:text,analysis:null,diagnosis:null,resolution:null,status,priority,history_title:update?"Telegram Update":"Task Created from Telegram",history_details:text,requires_confirmation:status==="CLOSED",reply:""}}
function hasConfirm(t){return /(?:\bconfirm(?:ed)?\b|\bapprove\b|أكد|اكد|تأكيد|تاكيد|مؤكد|نفذ)/i.test(t)}
function taskSummary(t){return `<b>#${t.task_number||"?"} ${esc(t.title||"")}</b>\nStatus: ${esc(t.status||"")} | Priority: ${esc(t.priority||"")}${t.due_date?`\nDue: ${esc(t.due_date)}`:""}`}
async function executeAction(env,ctx,a,raw){if(a.requires_confirmation&&!hasConfirm(raw))return `⚠️ I understood the action, but it needs confirmation.\nSend the same request again with <b>أكد</b> or <b>confirm</b>.`;if(a.action==="CREATE_TASK"){const payload={title:a.title||"New Task",description:a.description||raw,analysis:a.analysis||null,diagnosis:a.diagnosis||null,resolution:a.resolution||null,status:a.status||"NEW",priority:a.priority||"MEDIUM",start_date:new Date().toISOString().slice(0,10),created_by:ctx.user.id,updated_by:ctx.user.id,archived:false};const rows=await sb(env,ctx.token,"tasks",{method:"POST",prefer:"return=representation",body:payload});const t=rows?.[0];if(t?.id)await sb(env,ctx.token,"task_history",{method:"POST",body:{task_id:t.id,event_type:"TELEGRAM",title:a.history_title||"Task Created from Telegram",details:a.history_details||raw,created_by:ctx.user.id}});return `✅ Task created\n${taskSummary(t)}`}if(a.action==="QUERY_TASKS"){let q="tasks?archived=eq.false&select=*&order=updated_at.desc&limit=10";if(a.status)q+=`&status=eq.${a.status}`;if(a.priority)q+=`&priority=eq.${a.priority}`;const rows=await sb(env,ctx.token,q);if(!rows?.length)return "No matching tasks found.";return rows.map(taskSummary).join("\n\n")}if(["UPDATE_TASK","ADD_HISTORY"].includes(a.action)){if(!a.task_number)return "I need the Task number. Example: task 125.";const rows=await sb(env,ctx.token,`tasks?task_number=eq.${a.task_number}&select=*&limit=1`);const t=rows?.[0];if(!t)return `Task #${a.task_number} not found or not accessible.`;if(a.action==="UPDATE_TASK"){const patch={updated_by:ctx.user.id};for(const k of ["title","description","analysis","diagnosis","resolution","status","priority"])if(a[k]!=null)patch[k]=a[k];await sb(env,ctx.token,`tasks?id=eq.${t.id}`,{method:"PATCH",body:patch})}await sb(env,ctx.token,"task_history",{method:"POST",body:{task_id:t.id,event_type:"TELEGRAM",title:a.history_title||"Telegram update",details:a.history_details||raw,created_by:ctx.user.id}});const fresh=(await sb(env,ctx.token,`tasks?id=eq.${t.id}&select=*`))?.[0]||t;return `✅ Updated\n${taskSummary(fresh)}`}return a.reply||"Tell me what you want to create, update, search, or close."}

async function handleMessage(env,msg){if(!msg?.text)return;const chatId=msg.chat.id,from=msg.from,text=msg.text.trim();let ctx;try{ctx=await botContext(env)}catch(e){await say(env,chatId,e.message==="EMAIL_CONFIRMATION_REQUIRED"?"⚠️ TaskDesk bot account was created and needs email confirmation before first use.":`⚠️ ${esc(e.message)}`);return}if(text==="/start"||text.startsWith("/start ")){try{await claim(env,ctx,from,chatId,text.split(/\s+/)[1]||"");await say(env,chatId,`✅ <b>TaskDesk AI connected to your Telegram.</b>\n\nكلمني طبيعي عربي أو English.\nExamples:\n• اعمل تاسك إن العميل اشتكى من تقرير الرواتب\n• task 12 العميل رد وطلب تجربة جديدة\n• وريني التاسكات المفتوحة\n• أكد اقفل task 12\n\n${ctx.profile?.role==="ADMIN"?"Full TaskDesk access is active.":`Bot account role: ${esc(ctx.profile?.role||"MEMBER")}. It can fully manage tasks it creates; assign it to an existing task if you want it to update that task too.`}`)}catch(e){await say(env,chatId,`⚠️ ${esc(e.message)}`)}return}if(!(await ensureOwner(env,ctx,from))){await say(env,chatId,"🔒 This bot is private. Pair it first with /start + your pairing code.");return}if(text==="/help"){await say(env,chatId,"Send normal Arabic/English messages. I can create tasks, update tasks, add history, search, and change status. Closing requires confirmation.");return}try{const a=await interpret(env,text);const reply=await executeAction(env,ctx,a,text);await say(env,chatId,reply)}catch(e){await say(env,chatId,`⚠️ ${esc(e.message)}`)}}

export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==="/health")return Response.json({ok:true,service:"TaskDesk Telegram AI",configured:{telegram:!!env.TELEGRAM_BOT_TOKEN,email:!!env.SUPABASE_BOT_EMAIL,ai:!!env.AI}});if(url.pathname==="/setup"&&request.method==="GET"){if(url.searchParams.get("code")!==await pairCode(env))return new Response("forbidden",{status:403});const me=await telegram(env,"getMe",{});let auth={ok:false};try{const ctx=await botContext(env);auth={ok:true,user_id:ctx.user.id,role:ctx.profile?.role||null,active:ctx.profile?.is_active??null}}catch(e){auth={ok:false,error:String(e?.message||e)}}const target=`${url.origin}/`;await telegram(env,"setWebhook",{url:target,secret_token:await webhookSecret(env),drop_pending_updates:true});return Response.json({ok:true,bot:`@${me.username}`,webhook:target,auth})}if(request.method!=="POST")return new Response("TaskDesk Telegram AI",{status:200});if(request.headers.get("X-Telegram-Bot-Api-Secret-Token")!==await webhookSecret(env))return new Response("forbidden",{status:403});let update;try{update=await request.json()}catch{return new Response("bad request",{status:400})}if(update.message)await handleMessage(env,update.message);return new Response("ok",{status:200})}};
