const JSON_HEADERS={"content-type":"application/json;charset=UTF-8"};
const SCHEMA={type:"object",properties:{action:{type:"string",enum:["CREATE_TASK","UPDATE_TASK","ADD_HISTORY","QUERY_TASKS","HELP","UNKNOWN"]},task_number:{type:["integer","null"]},title:{type:["string","null"]},description:{type:["string","null"]},analysis:{type:["string","null"]},diagnosis:{type:["string","null"]},resolution:{type:["string","null"]},status:{type:["string","null"],enum:["NEW","IN_PROGRESS","WAITING","BLOCKED","RESOLVED","CLOSED","CANCELLED",null]},priority:{type:["string","null"],enum:["LOW","MEDIUM","HIGH","URGENT",null]},history_title:{type:["string","null"]},history_details:{type:["string","null"]},requires_confirmation:{type:"boolean"},reply:{type:"string"}},required:["action","task_number","title","description","analysis","diagnosis","resolution","status","priority","history_title","history_details","requires_confirmation","reply"]};

function tgUrl(env,method){return `https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/${method}`}
async function telegram(env,method,body){const r=await fetch(tgUrl(env,method),{method:"POST",headers:JSON_HEADERS,body:JSON.stringify(body)});const d=await r.json();if(!d.ok)throw new Error(d.description||"Telegram error");return d.result}
async function say(env,chatId,text,extra={}){return telegram(env,"sendMessage",{chat_id:chatId,text,parse_mode:"HTML",disable_web_page_preview:true,...extra})}
function esc(s=""){return String(s).replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]))}

async function auth(env){const login=async()=>{const r=await fetch(`${env.SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:env.SUPABASE_ANON_KEY,...JSON_HEADERS},body:JSON.stringify({email:env.SUPABASE_BOT_EMAIL,password:env.SUPABASE_BOT_PASSWORD})});const d=await r.json();return {ok:r.ok,data:d}};let x=await login();if(x.ok)return x.data;if(!String(x.data?.message||x.data?.error_description||"").toLowerCase().includes("invalid"))throw new Error(x.data?.message||x.data?.error_description||"Supabase login failed");const sr=await fetch(`${env.SUPABASE_URL}/auth/v1/signup`,{method:"POST",headers:{apikey:env.SUPABASE_ANON_KEY,...JSON_HEADERS},body:JSON.stringify({email:env.SUPABASE_BOT_EMAIL,password:env.SUPABASE_BOT_PASSWORD,data:{full_name:"TaskDesk Telegram Bot"}})});const sd=await sr.json();if(sd.access_token)return sd;throw new Error("Bot account created but needs activation. Open TaskDesk and authorize the bot account once.")}
async function sb(env,token,path,{method="GET",body,prefer}={}){const h={apikey:env.SUPABASE_ANON_KEY,authorization:`Bearer ${token}`};if(body!==undefined)Object.assign(h,JSON_HEADERS);if(prefer)h.Prefer=prefer;const r=await fetch(`${env.SUPABASE_URL}/rest/v1/${path}`,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.hint||`Supabase ${r.status}`);return d}
async function botContext(env){const a=await auth(env);const token=a.access_token,user=a.user;const ps=await sb(env,token,`profiles?id=eq.${user.id}&select=*`);return {token,user,profile:ps?.[0]||null}}

async function config(env,ctx){const rows=await sb(env,ctx.token,`tasks?title=eq.__TELEGRAM_CONFIG__&created_by=eq.${ctx.user.id}&archived=eq.true&select=*`);if(!rows?.length)return null;try{return JSON.parse(rows[0].description||"{}") }catch{return null}}
async function claim(env,ctx,from,chatId){const c=await config(env,ctx);if(c?.telegram_user_id&&String(c.telegram_user_id)!==String(from.id))throw new Error("This bot is already paired with another Telegram account.");if(!c){await sb(env,ctx.token,"tasks",{method:"POST",prefer:"return=representation",body:{title:"__TELEGRAM_CONFIG__",description:JSON.stringify({telegram_user_id:from.id,chat_id:chatId,username:from.username||null,paired_at:new Date().toISOString()}),status:"CLOSED",priority:"LOW",start_date:new Date().toISOString().slice(0,10),created_by:ctx.user.id,updated_by:ctx.user.id,archived:true}})}return true}
async function ensureOwner(env,ctx,from){const c=await config(env,ctx);return !!c&&String(c.telegram_user_id)===String(from.id)}

async function interpret(env,text){const system=`You are TaskDesk Copilot. The user may speak Egyptian/Gulf Arabic, English, mixed Arabic-English, or informal shorthand. Convert requests into ONE safe structured action. Create professional business wording. Default task content language: professional English unless the user explicitly asks for Arabic. Never invent facts. For update/add-history requests, require a task number if not clear. Closing/cancelling requires explicit confirmation words such as confirm/confirmed/أكد/تأكيد; otherwise set requires_confirmation=true. Status mapping: جديد=NEW, شغال/قيد العمل=IN_PROGRESS, انتظار/مستني=WAITING, blocked/متوقف=BLOCKED, اتحل=RESOLVED, اقفل/closed=CLOSED. Return only schema JSON.`;
const out=await env.AI.run(env.AI_MODEL||"@cf/meta/llama-3.1-8b-instruct-fast",{messages:[{role:"system",content:system},{role:"user",content:text}],response_format:{type:"json_schema",json_schema:SCHEMA},temperature:.2,max_tokens:700});return out.response}
function hasConfirm(t){return /(?:\bconfirm(?:ed)?\b|\bapprove\b|أكد|تأكيد|مؤكد|نفذ)/i.test(t)}
function taskSummary(t){return `<b>#${t.task_number||"?"} ${esc(t.title||"")}</b>\nStatus: ${esc(t.status||"")} | Priority: ${esc(t.priority||"")}${t.due_date?`\nDue: ${esc(t.due_date)}`:""}`}
async function executeAction(env,ctx,a,raw){if(a.requires_confirmation&&!hasConfirm(raw))return `⚠️ I understood the action, but it needs confirmation.\nSend the same request again with <b>أكد</b> or <b>confirm</b>.`;
if(a.action==="CREATE_TASK"){const payload={title:a.title||"New Task",description:a.description||raw,analysis:a.analysis||null,diagnosis:a.diagnosis||null,resolution:a.resolution||null,status:a.status||"NEW",priority:a.priority||"MEDIUM",start_date:new Date().toISOString().slice(0,10),created_by:ctx.user.id,updated_by:ctx.user.id,archived:false};const rows=await sb(env,ctx.token,"tasks",{method:"POST",prefer:"return=representation",body:payload});const t=rows?.[0];if(a.history_title&&t?.id)await sb(env,ctx.token,"task_history",{method:"POST",body:{task_id:t.id,event_type:"TELEGRAM",title:a.history_title,details:a.history_details||raw,created_by:ctx.user.id}});return `✅ Task created\n${taskSummary(t)}`}
if(a.action==="QUERY_TASKS"){let q="tasks?archived=eq.false&select=*&order=updated_at.desc&limit=10";if(a.status)q+=`&status=eq.${a.status}`;if(a.priority)q+=`&priority=eq.${a.priority}`;const rows=await sb(env,ctx.token,q);if(!rows?.length)return "No matching tasks found.";return rows.map(taskSummary).join("\n\n")}
if(["UPDATE_TASK","ADD_HISTORY"].includes(a.action)){if(!a.task_number)return "I need the Task number. Example: task 125.";const rows=await sb(env,ctx.token,`tasks?task_number=eq.${a.task_number}&select=*&limit=1`);const t=rows?.[0];if(!t)return `Task #${a.task_number} not found or not accessible.`;
if(a.action==="UPDATE_TASK"){const patch={updated_by:ctx.user.id};for(const k of ["title","description","analysis","diagnosis","resolution","status","priority"])if(a[k]!=null)patch[k]=a[k];await sb(env,ctx.token,`tasks?id=eq.${t.id}`,{method:"PATCH",body:patch});}
if(a.history_title||a.history_details||a.action==="ADD_HISTORY")await sb(env,ctx.token,"task_history",{method:"POST",body:{task_id:t.id,event_type:"TELEGRAM",title:a.history_title||"Telegram update",details:a.history_details||raw,created_by:ctx.user.id}});const fresh=(await sb(env,ctx.token,`tasks?id=eq.${t.id}&select=*`))?.[0]||t;return `✅ Updated\n${taskSummary(fresh)}`}
return a.reply||"Tell me what you want to create, update, search, or close."}

async function handleMessage(env,msg){if(!msg?.text)return;const chatId=msg.chat.id,from=msg.from,text=msg.text.trim();let ctx;try{ctx=await botContext(env)}catch(e){await say(env,chatId,`⚠️ ${esc(e.message)}`);return}
if(text==="/start"||text.startsWith("/start ")){try{await claim(env,ctx,from,chatId);await say(env,chatId,`✅ <b>TaskDesk AI connected to your Telegram.</b>\n\nYou can speak naturally in Arabic or English.\nExamples:\n• اعمل تاسك إن العميل اشتكى من تقرير الرواتب\n• task 12 العميل رد وطلب تجربة جديدة\n• وريني التاسكات المفتوحة\n• أكد اقفل task 12\n\n${ctx.profile?.role==="ADMIN"?"Full TaskDesk access is active.":`⚠️ Bot account role is currently ${esc(ctx.profile?.role||"MEMBER")}. It can create its own tasks now; authorize it as Admin in TaskDesk to update/search all existing tasks.`}`)}catch(e){await say(env,chatId,`⚠️ ${esc(e.message)}`)}return}
if(!(await ensureOwner(env,ctx,from))){await say(env,chatId,"🔒 This bot is private. Send /start from the owner's Telegram account first.");return}
if(text==="/help"){await say(env,chatId,"Send normal Arabic/English messages. I can create tasks, update tasks, add history, search, and change status. Closing/cancelling requires confirmation.");return}
try{const a=await interpret(env,text);const reply=await executeAction(env,ctx,a,text);await say(env,chatId,reply)}catch(e){await say(env,chatId,`⚠️ ${esc(e.message)}`)}}

export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==="/health")return new Response(JSON.stringify({ok:true,service:"TaskDesk Telegram AI"}),{headers:JSON_HEADERS});if(request.method!=="POST")return new Response("TaskDesk Telegram AI",{status:200});if(env.TELEGRAM_WEBHOOK_SECRET&&request.headers.get("X-Telegram-Bot-Api-Secret-Token")!==env.TELEGRAM_WEBHOOK_SECRET)return new Response("forbidden",{status:403});let update;try{update=await request.json()}catch{return new Response("bad request",{status:400})}if(update.message)await handleMessage(env,update.message);return new Response("ok",{status:200})}};
